const categories = [
    {
      category: "Novidades",
      subcategory: [
        {
          name: "NOVIDADES",
          list: [
            "Vestidos",
            "Blusas",
            "Calças",
            "Camisetas",
            "Saias & Shorts",
            "Blazers",
            "Casacos & Jaquetas",
            "Sapatos",
            "Moda Praia",
            "Moda Fitness",
          ],
        },
        {
          name: "ROUPAS PARA TRABALHAR",
          list: [
            "Blazers",
            "Blusas Sociais",
            "Calças Alfaiataria",
            "Camisas",
            "Macacões Sociais",
            "Saias Sociais",
            "Sapatos Sociais",
            "Terninhos",
            "Vestidos Sociais",
          ],
        },
        {
          name: "MAIS VENDIDOS",
          list: [
            "Mais Vendidos de Moda",
            "Mais Vendidos de Beleza",
            "Mais Vendidos de Casa",
          ],
        },
        {
          name: "NOVIDADES EM MARCAS PARCEIRAS",
          list: [
            "Trizi",
            "Ce.ci",
            "Beatnik & Sons",
            "Ziovara",
            "Marcas Favoritas",
          ],
        },
      ],
    },
    {
      name: "Roupas",
      category: "Roupas",
      subcategory: [
        {
          name: "LOOK INTEIRO",
          list: [
            "Tudo em Roupas",
            "Peças Essenciais",
            "Macacão e Macaquinho",
            "Vestidos",
            "Vestidos Curtos",
            "Vestidos Midi e Médios",
            "Vestidos Longos",
            "Vestidos de Festa",
          ],
        },
        {
          name: "PARTES DE CIMA",
          list: [
            "Tudo em Partes de Cima",
            "Casacos & Jaquetas",
            "Blazers",
            "Blusas",
            "T-Shirts & Camisetas",
            "Camisas",
            "Body",
            "Suéteres & Cardigans",
            "Coletes",
            "Croppeds",
            "Regatas",
          ],
        },
        {
          name: "PARTES DE BAIXO",
          list: [
            "Tudo em Partes de Baixo",
            "Calças",
            "Calças Jeans",
            "Calças Jogger",
            "Calças Moletom",
            "Calças Pantalona",
            "Calças Retas & Skinny",
            "Calças de Alfaiataria",
            "Saias",
            "Saias Curtas",
            "Saias Midi e Médias",
            "Saias Longas",
            "Shorts e Bermudas",
          ],
        },
        {
          name: "LINGERIE",
          list: [
            "Tudo em Lingerie",
            "Body Lingerie",
            "Calcinhas",
            "Calcinhas Absorventes",
            "Sutiãs",
            "Pijamas",
            "Meias",
          ],
        },
        {
          name: "MODA PRAIA",
          list: [
            "Tudo em Moda Praia",
            "Tops de Biquíni",
            "Calcinhas de Biquíni",
            "Maiôs",
            "Saídas de Praia",
            "Toalhas de Praia",
          ],
        },
        {
          name: "MODA FITNESS",
          list: [
            "Tudo em Moda Fitness",
            "Camisetas Fitness",
            "Jaquetas e Casacos Fitness",
            "Leggings e Calças Fitness",
            "Shorts e Saias Fitness",
            "Tops Fitness",
          ],
        },
      ],
    },
    {
      name: "Sapato",
      category: "Sapato",
      subcategory: [
        {
          name: "CATEGORIAS",
          list: [
            "Tudo em Sapatos",
            "Botas",
            "Chinelos",
            "Mocassins",
            "Papetes",
            "Rasteiras",
            "Sandálias",
            "Scarpins",
            "Tênis",
          ],
        },
      ],
    },
    {
      name: "Casa",
      category: "Casa",
      subcategory: [],
    },
    {
      name: "Beleza",
      category: "Beleza",
      subcategory: [],
    },
    {
      name: "Promoções",
      category: "Promoções",
      subcategory: [],
    },
  ];